/**
 * EMERGENCY PROCEDURES — transcribed in full from the old members' site:
 *   safety/MainGd.asp                          (the decision page)
 *   safety/EmrgcyGdnc/SERIOUS_ACCDNT_2025Jan.asp   (revised Jan 2025)
 *   safety/EmrgcyGdnc/report_crash_2019A.htm
 *   safety/EmrgcyGdnc/glider_missing_2019A.htm
 *   safety/EmrgcyGdnc/personal_injury_2025_Jan5.htm (revised Jan 2025)
 *
 * ⚠️  SAFETY-CRITICAL CONTENT. The Safety Officer must check every word and
 * every telephone number against the club's published procedure before this
 * page is relied upon. Several hospital numbers in the source pages have
 * irregular digit counts (see `verify` flags) and are reproduced here exactly
 * as the old site had them rather than being "corrected" by guesswork.
 *
 * Do not edit this file to make the wording nicer. It is a transcription.
 */

export type Step = { text: string; detail?: string; emphasis?: boolean };

export type Procedure = {
  slug: string;
  when: string;
  title: string;
  intro?: string;
  steps: Step[];
  after?: string[];
  source: string;
  revised?: string;
};

export const RED_BOX =
  'The SERIOUS ACCIDENT — ACTION PLAN is kept in the RED Team Kit Box in the LAUNCH POINT VEHICLE.';

export const procedures: Procedure[] = [
  {
    slug: 'crash-on-airfield',
    when: 'A glider has crashed on or near Camphill airfield',
    title: 'Serious accident — glider crash on or near the airfield',
    intro:
      'In the event of a glider crash on or near the airfield which does, or may, involve serious injury to anyone.',
    steps: [
      { text: 'Dial 999 (or 112).', emphasis: true },
      {
        text: 'Ask the operator for the FIRE AND RESCUE SERVICE.',
        detail: 'They are nearest and they carry paramedics.',
        emphasis: true,
      },
      { text: 'Tell them: “SERIOUS GLIDER CRASH”.' },
      {
        text: 'Say where you are calling from.',
        detail:
          'The Gliding Club, Great Hucklow, near Tideswell, near Buxton, SK17 8RQ.',
      },
      {
        text: 'Give the club location.',
        detail: '2 miles north-east of the road junction of the B6049 with the A623.',
      },
      {
        text: 'Give the crash location.',
        detail:
          'On the club airfield, or the approximate distance and direction from the airfield.',
      },
      { text: 'Say how many may be injured.' },
      { text: 'Say how many may be trapped.' },
      { text: 'Also ask for the AMBULANCE SERVICE.' },
      {
        text: 'Also ask for the MOUNTAIN RESCUE TEAM if the crash site is difficult to reach.',
      },
      { text: 'Say where the emergency services will be met, if possible.' },
      {
        text: 'Stay by the phone after the call.',
        detail: 'Until the emergency services arrive, in case someone rings back.',
        emphasis: true,
      },
      {
        text: 'Then open the RED Team Kit Box and follow the Emergencies Action Plan.',
        detail: 'The red box is kept in the Launch Point vehicle.',
        emphasis: true,
      },
    ],
    source: 'https://dlgc.org.uk/members/safety/EmrgcyGdnc/SERIOUS_ACCDNT_2025Jan.asp',
    revised: 'January 2025',
  },
  {
    slug: 'personal-injury',
    when: 'Someone is injured or ill, and no aircraft is involved',
    title: 'Personal injury or illness (no aircraft involved)',
    steps: [
      {
        text: 'If a doctor is required, ring the surgery at Eyam: 01433 631628.',
        detail: 'The surgery is on Church Street in Eyam village.',
      },
      {
        text: 'If more urgent treatment is needed, call an ambulance on 999.',
        emphasis: true,
      },
      {
        text: 'You will be asked where you are calling from.',
        detail:
          'The Gliding Club, Great Hucklow, near Tideswell. Post code SK17 8RQ. Nearest classified road: B6049.',
      },
      {
        text: 'If the injury is serious, put the Serious Accident Action Plan into effect as far as is practicable.',
        detail: RED_BOX,
        emphasis: true,
      },
      {
        text: 'If the injured person goes to hospital, make sure next of kin are notified.',
        detail: 'Either by a friend, or by asking the police to notify them.',
      },
      { text: 'Report any accident to the club’s Health & Safety Officer.' },
    ],
    source: 'https://dlgc.org.uk/members/safety/EmrgcyGdnc/personal_injury_2025_Jan5.htm',
    revised: 'January 2025',
  },
  {
    slug: 'remote-crash',
    when: 'A crash is reported in a field away from Camphill',
    title: 'Remote crash — a report of an aircraft down away from Camphill',
    intro:
      'Collect as much information as possible, to identify the aircraft or its pilot and establish whether the club must act.',
    steps: [
      { text: 'Have the pilot or pilots been identified?' },
      { text: 'Is it a glider, or an aeroplane with an engine?' },
      { text: 'Are there aircraft registration letters or numbers?' },
      { text: 'What is the colour scheme?' },
      { text: 'Is the aircraft type known?' },
      {
        text: 'What action has been taken so far?',
        detail: 'For example, have the emergency services been notified?',
      },
      { text: 'Are there contact names and telephone numbers for the emergency services?' },
      { text: 'What is the location of the accident, and the best way to get to it?' },
      { text: 'Are there difficulties with access to the location?' },
      { text: 'Names and addresses of eye witnesses?' },
      { text: 'Name of any police officer in charge of the incident?' },
    ],
    after: [
      'If the aircraft IS from Camphill: put the club’s Serious Accident Action Plan into effect as far as is practicable and appropriate. ' +
        RED_BOX,
      'If the aircraft is NOT from Camphill: contact the Watch Supervisor at London Air Traffic Control Centre (LATCC) on 01895 445566, and give as much information as you can to help them find the airfield the aircraft came from.',
    ],
    source: 'https://dlgc.org.uk/members/safety/EmrgcyGdnc/report_crash_2019A.htm',
  },
  {
    slug: 'glider-missing',
    when: 'A glider is missing at the end of the day, or overdue at any time',
    title: 'Glider missing at end of day, or overdue',
    intro:
      'Applies at the end of flying, or at any time if a glider is overdue while flown by an inexperienced pilot, or overdue on a short task by a pilot of any experience. First make sure the glider really is overdue.',
    steps: [
      { text: 'Does the flying log show no landing?' },
      { text: 'Is the glider not in the hangar, the trailer park, or its own trailer?' },
      {
        text: 'Has the pilot left their intentions and mobile number with anybody at the club?',
      },
      {
        text: 'Has nothing been heard from the pilot by anyone at the launch point, clubhouse or office?',
      },
      {
        text: 'Is there any indication of the glider’s location on Spot the Gliders or Glider Radar?',
      },
      { text: 'Have attempts been made to contact the pilot by radio or mobile phone?' },
      {
        text: 'Is the pilot known to carry FLARM or a personal locator beacon (PLB)?',
      },
      {
        text: 'Bear in mind an experienced pilot on a long task — perhaps in a turbo — may arrive back after 8:00pm or later.',
      },
    ],
    after: [
      'If, after those checks, the glider is considered overdue, the following action must be taken BEFORE SUNSET.',
      '1. Make sure the Duty Flying Instructor is aware and is taking responsibility, and will inform the CFI and Launch Marshal.',
      '2. Telephone the Distress and Diversion cell on 01489 612691 and explain the problem. D&D will immediately take responsibility for dealing with the situation.',
      '3. If the glider returns, or a report explains its whereabouts, inform D&D on 01489 612691 immediately, then the CFI, DFI and Launch Marshal.',
      '4. If a crash is reported and the aircraft is identified as from Camphill, follow the Serious Accident Action Plan as far as practical and appropriate. ' +
        RED_BOX,
    ],
    source: 'https://dlgc.org.uk/members/safety/EmrgcyGdnc/glider_missing_2019A.htm',
  },
];

/**
 * Hospital and casualty departments, from the personal injury procedure.
 * `verify: true` marks a number whose digit count looks wrong in the source
 * page. Left exactly as published rather than guessed at — the Safety Officer
 * must confirm these.
 */
export const hospitals = {
  ae: [
    { name: 'Chesterfield Royal Hospital', where: 'Calow, Chesterfield', tel: '01246 2772711', verify: true },
    { name: 'Northern General Hospital', where: 'Herries Road, Sheffield', tel: '01142 4343433', verify: true },
    { name: 'Stepping Hill Hospital', where: 'Poplar Grove, London Road, Stockport', tel: '0161 483 10100', verify: true },
  ],
  minor: [
    { name: 'Buxton Hospital', where: 'London Road, Buxton', tel: '01298 214000', verify: true },
    { name: 'Royal Hallamshire Hospital', where: 'Glossop Road, Sheffield', tel: '01142 711900', verify: true },
  ],
  note: 'It is worth ringing a Minor Injuries Unit first to see whether they can deal with the injury.',
};

export const emergencyContacts = [
  { label: 'Emergency services', tel: '999', note: 'Or 112. Ask for Fire and Rescue first — nearest, with paramedics.' },
  { label: 'Eyam Surgery', tel: '01433 631628', note: 'Church Street, Eyam — if a doctor is required' },
  { label: 'Distress & Diversion cell', tel: '01489 612691', note: 'Glider missing or overdue' },
  { label: 'London ATC Centre (LATCC)', tel: '01895 445566', note: 'Watch Supervisor — remote crash, aircraft not from Camphill' },
];
