/**
 * ROLES AND ROLE HOLDERS — who does what at Camphill, from job&roles.asp.
 *
 * GENERATED by tools/parse-roles.mjs. Hand edits are fine and expected: this
 * list goes out of date the moment somebody stands down.
 *
 * NAMES ONLY. No telephone numbers, no email addresses. The club publishes who
 * holds a role so members know who to ask; contact details live in Members'
 * Admin, and putting them here would breach CLAUDE.md rule 6.
 *
 * "VACANT" is meaningful — it is how the club advertises that it needs someone.
 * Do not tidy those rows away.
 */

export type Role = {
  role: string;
  /** What the role actually covers, in the club's own shorthand. */
  remit: string;
  holders: string[];
};

/** Last updated on the old site. */
export const rolesUpdated = "9/6/26";

export const roles: Role[] = [
  { role: "Airfield Officer", remit: "Airfield, peri-track", holders: ["Belle Tyler"] },
  { role: "Airspace", remit: "NATS, BGA liaison", holders: ["Dave Salmon", "Mike Armstrong", "Phil Maund", "Chris Dawes"] },
  { role: "Bar", remit: "Stock and pricing", holders: ["John Sconce"] },
  { role: "BGA Inspectors", remit: "Airworthiness authority", holders: ["Warwick Horne", "Colin Taylor"] },
  { role: "BGA Duplicate Inspectors", remit: "Checking inspections", holders: ["Peter Gray", "Dave Upcott", "Mike Armstrong", "Paul Smith", "Steve Marlor"] },
  { role: "BGA Ladder", remit: "Stewardship", holders: ["John McKenzie"] },
  { role: "Blake-Robertshaw Trophy", remit: "Brieings, results", holders: ["Owen Brown"] },
  { role: "Camphill s", remit: "Prepare, edit and publish", holders: ["Peter Gill"] },
  { role: "Canopies", remit: "Canopy cleaning instructions & kits", holders: ["Peter Gray"] },
  { role: "Chief Clerk", remit: "Oversight and guidance re duty clerks role", holders: ["Jingtian Wang"] },
  { role: "Chief Launch Marshal", remit: "Launch point safety and efficiency", holders: ["Stuart MacArthur"] },
  { role: "Child Protection Officer", remit: "DBS checks and CP policy compliance", holders: ["Andrew Hawton"] },
  { role: "Data Protection Officer", remit: "DP policy compliance", holders: ["Liz Martin"] },
  { role: "Deputy CFIs", remit: "Assistants to the CFI", holders: ["Brian Allen", "Richard Dance", "Alan Jolly"] },
  { role: "Deputy Chief Launch Marshal", remit: "Assistant to the CLM", holders: ["Bob Carlisle"] },
  { role: "Duty Rota Secretary", remit: "Duty rotas for instructors, launch marshals, winch drivers and duty clerks.", holders: ["Steve Pearce"] },
  { role: "Head Librarian", remit: "Custodain of club's literature store", holders: ["Mike Armstrong *new"] },
  { role: "First Aid Officer", remit: "First aid, defibrillator,first aid training liason", holders: ["Jan Rush"] },
  { role: "Free Flight & Members' Admin", remit: "On-line IT system support", holders: ["Mo Bent"] },
  { role: "Health & Safety", remit: "Non-flying H&S", holders: ["Alex Sariban"] },
  { role: "Induction Courses", remit: "Organisation and delivery", holders: ["Tony Kay", "Roger Lucas"] },
  { role: "Insurance Officer", remit: "Insurance administration", holders: ["Alex Oldham"] },
  { role: "Inter-Club League", remit: "Fixtures, teams", holders: ["Jonathan Thorpe"] },
  { role: "Junior Gliding", remit: "Liaison officer", holders: ["Meurig Thomas"] },
  { role: "Medicals Monitor", remit: "Procedures oversight", holders: ["Dave Upcott"] },
  { role: "Membership Officer", remit: "", holders: ["Colin Harper *new"] },
  { role: "Members' Champion", remit: "Contact with committee", holders: ["Peter Gill"] },
  { role: "Mentor Scheme", remit: "Coordinator of ground training", holders: ["Paul Smith"] },
  { role: "Overflight Reporter", remit: "Passing reports to BGA", holders: ["John Illidge"] },
  { role: "Parachutes", remit: "Re-packing & interim inspections", holders: ["Mike Armstrong"] },
  { role: "Pilot Medicals", remit: "Arrangements & if required, chaperone", holders: ["Liz Martin"] },
  { role: "RT Courses", remit: "Organisation", holders: ["VACANT"] },
  { role: "Sailplane & Gliding Correspondent", remit: "Club news", holders: ["Peter Gill"] },
  { role: "Safety Officer (Flying)", remit: "Flying and aircraft safety", holders: ["Bob Bollom"] },
  { role: "Shock Ropes", remit: "Assembly & stock", holders: ["VACANT"] },
  { role: "Simulator", remit: "Development team leader", holders: ["Brian Allen"] },
  { role: "Silver Seekers", remit: "Coordinator", holders: ["John McKenzie"] },
  { role: "Social Media", remit: "Oversight and support", holders: ["Nikhil Paradkar"] },
  { role: "Strops, Weak Links, Parachutes", remit: "Assembly & stock", holders: ["VACANT"] },
  { role: "Technical Officer", remit: "Club aircraft mntnc admin & BGA contact", holders: ["Dave Upcott"] },
  { role: "Trophies Steward", remit: "Club trophies mngt., scoring, awarding", holders: ["Andrew Hawton"] },
  { role: "Vintage Rally Organiser", remit: "Publicity, admin, etc", holders: ["Mike Armstrong", "& Steve Marlor"] },
  { role: "WhatsApp Group Administrator", remit: "Membership,etc", holders: ["Paul Smith"] },
  { role: "Website (Members)", remit: "Editing & content", holders: ["Bob Bollom"] },
  { role: "Website (Public)", remit: "Editing & content", holders: ["Martin Willcox"] },
  { role: "Winch Master", remit: "Winch training", holders: ["John Shannon"] },
  { role: "Winch Master's Deputy", remit: "Winch training", holders: ["Andrew Hawton"] },
  { role: "Winch Safety Officer", remit: "Winch safety checks", holders: ["VACANT"] },
];

export const vacantRoles = roles.filter((r) => r.holders.some((h) => /vacant/i.test(h)));

export const rolesSource = 'https://www.dlgc.org.uk/members/job&roles.asp';

/** Committee roles are maintained separately, as they were on the old site. */
export const committeeSource = 'https://www.dlgc.org.uk/members/committee2026.2.asp';
