/**
 * Builds src/content/roles.ts from the old site's job&roles.asp.
 *
 * NAMES ONLY, no contact details. The club publishes who holds each role so a
 * member knows who to ask; it does not publish their phone numbers, and neither
 * do we (CLAUDE.md rule 6). If a role holder wants to be contactable, that goes
 * through the office.
 *
 * Run: node tools/parse-roles.mjs > src/content/roles.ts
 */
import fs from 'node:fs';

const SRC = '/mnt/user-data/uploads/dlgc-mirror/www.dlgc.org.uk/members/job&roles.asp';
const raw = fs.readFileSync(SRC, 'utf8');

const ENT = [
  [/&nbsp;/gi, ' '], [/&amp;/gi, '&'], [/&lt;/gi, '<'], [/&gt;/gi, '>'],
  [/&quot;/gi, '"'], [/&#39;/g, "'"], [/&rsquo;/gi, '’'], [/&ldquo;/gi, '“'], [/&rdquo;/gi, '”'],
];
const decode = (s) => ENT.reduce((a, [r, t]) => a.replace(r, t), s).replace(/&#(\d+);/g, (_, d) => String.fromCharCode(+d));

const INLINE = 'span|font|strong|b|em|i|u|sup|sub|small|big|a|o:p';
const joinWords = (s) => {
  let out = s;
  for (let i = 0; i < 6; i++) {
    const next = out.replace(new RegExp(`(\\w)(?:<\\/?(?:${INLINE})\\b[^>]*>)+(?=\\w)`, 'gi'), '$1');
    if (next === out) break;
    out = next;
  }
  return out;
};

/** Split on real line breaks — several roles are held by more than one person. */
const lines = (cell) =>
  decode(joinWords(cell).replace(/<br\s*\/?>|<\/p>|<\/div>/gi, '').replace(/<[^>]+>/g, ' '))
    .split('')
    .map((p) => p.replace(/\s+/g, ' ').trim())
    .filter(Boolean);

const flat = (cell) => lines(cell).join(' ');

/**
 * A few cells on the old page put two names on one line with no break, so the
 * split above cannot see them. Explicit, auditable corrections rather than a
 * clever rule that would eventually mangle a genuine three-part name.
 */
const SPLIT_FIX = {
  'Warwick Horne Colin Taylor': ['Warwick Horne', 'Colin Taylor'],
};

const tables = raw.match(/<table[\s\S]*?<\/table>/gi) ?? [];
const table = tables.sort((a, b) => b.length - a.length)[0];

const roles = [];
for (const row of table.match(/<tr[\s\S]*?<\/tr>/gi) ?? []) {
  const cells = row.match(/<t[dh][\s\S]*?<\/t[dh]>/gi) ?? [];
  if (cells.length < 2) continue;
  const role = flat(cells[0]).replace(/\*?new/gi, '').trim();
  if (!role || /^role$/i.test(role)) continue;
  const remit = cells.length >= 3 ? flat(cells[1]) : '';
  const holders = lines(cells[cells.length - 1])
    .filter((h) => h.length > 1 && !/^name$/i.test(h))
    .flatMap((h) => SPLIT_FIX[h] ?? [h]);
  roles.push({ role, remit, holders });
}

const updated = (flat(raw).match(/Last update:\s*([0-9/]+)/i) ?? [])[1] ?? '';

const q = (s) => JSON.stringify(s);
process.stdout.write(`/**
 * ROLES AND ROLE HOLDERS — who does what at Camphill, from job&roles.asp.
 *
 * GENERATED by tools/parse-roles.mjs. Hand edits are fine and expected: this
 * list goes out of date the moment somebody stands down.
 *
 * NAMES ONLY. No telephone numbers, no email addresses. The club publishes who
 * holds a role so members know who to ask; contact details live in Members'
 * Admin, and putting them here would breach CLAUDE.md rule 6.
 *
 * "VACANT" is meaningful — it is how the club advertises that it needs someone.
 * Do not tidy those rows away.
 */

export type Role = {
  role: string;
  /** What the role actually covers, in the club's own shorthand. */
  remit: string;
  holders: string[];
};

/** Last updated on the old site. */
export const rolesUpdated = ${q(updated)};

export const roles: Role[] = [
${roles.map((r) => `  { role: ${q(r.role)}, remit: ${q(r.remit)}, holders: [${r.holders.map(q).join(', ')}] },`).join('\n')}
];

export const vacantRoles = roles.filter((r) => r.holders.some((h) => /vacant/i.test(h)));

export const rolesSource = 'https://www.dlgc.org.uk/members/job&roles.asp';

/** Committee roles are maintained separately, as they were on the old site. */
export const committeeSource = 'https://www.dlgc.org.uk/members/committee2026.2.asp';
`);

process.stderr.write(`roles: ${roles.length}\nvacant: ${roles.filter((r) => r.holders.some((h) => /vacant/i.test(h))).length}\nupdated: ${updated}\n`);
